type: gptsovits
api_endpoint: http://127.0.0.1:8001/stream
api_key: empty
request_header: {}
request_body:
  ref_audio_path: Voice/boy_refer.wav
  prompt_text: 我叫小黑，我也是妖精。
  prompt_lang: zh
  text_lang: zh
  batch_size: 8
  split_bucket: false
  parallel_infer: true
