type: openai
api_endpoint: http://127.0.0.1:8000/v1/chat/completions
api_key: empty
request_header: {}
request_body:
  model: Qwen3-8B
  max_tokens: 4096
  temperature: 0.7
  top_p: 0.8
  top_k: 20
  min_p: 0
  chat_template_kwargs:
    enable_thinking: false
RAG:
  enable: false
  embedding:
    api_endpoint: http://127.0.0.1:8000/v1
    model: bge-m3
    api_key: empty
  top_k: 3
